name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=10:y=10:w=10:h=10"
                        INDEX: 12
                        EPISODE_INDEX: 1,2,3,4,5,6
                        URLS: https://v26-default.ixigua.com/72c722bd3bad4383734f545bb192fcce/62f34ab6/video/tos/cn/tos-cn-v-0064/05dbfae62d6f4907b07d9c2804330206/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/411a81944b194c29b9096cf98c6b8869/62f34a2c/video/tos/cn/tos-cn-v-0064/61db4386bd4649ca8086fe56a038ea5b/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/70892a9549ef4aac6c1892b335320965/62f34a0c/video/tos/cn/tos-cn-v-0064/6f90040f1e9f43b29040dcbe7b3047d2/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/0506477702a87ab56f0051c49572bdfd/62f34a62/video/tos/cn/tos-cn-v-0064/04a44a3a0e7f405bbd84e6321441c6f6/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/9900e896aed46c6a0479d03af62f08ca/62f34a4f/video/tos/cn/tos-cn-v-0064/d441790ce4f646a6a948fd7feeb07ce0/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/8e45b1ffdf3ef22761c704508f4080b4/62f34814/video/tos/cn/tos-cn-v-0064/1987ed38f6ed463b85d159ce7aa9673e/?tg=?zxzj.vip&filename=540P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
