name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        TBN: 16K
                        POSITION: "delogo=x=10:y=10:w=10:h=10"
                        INDEX: 12
                        EPISODE_INDEX: 1
                        URLS: https://v3-default.ixigua.com/3f1096f57d93babd29a1efcd889cab03/62f2af39/video/tos/cn/tos-cn-v-0064/1987ed38f6ed463b85d159ce7aa9673e/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
