name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=10:w=1100:h=200"
                        INDEX: 12
                        EPISODE_INDEX: 1,2,3,4,5,6
                        URLS: https://v26-default.ixigua.com/51b6c79be8f70beef77e2b03bd0e70c1/62f28133/video/tos/cn/tos-cn-v-0064/05dbfae62d6f4907b07d9c2804330206/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4;https://v3-default.ixigua.com/64ff033e80d8a0dfeff75108b8cbb922/62f28284/video/tos/cn/tos-cn-v-0064/61db4386bd4649ca8086fe56a038ea5b/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4;https://qv24vqsnp7gq6m7fi40hrj2ejsh008e9h8b1raj56gl7thia4vpvvkvt.tt.x.bsgslb.cn/xdispatch70f05392ddcca2ed/v9-default.ixigua.com/6cfe3c9e7e9214a69013e91f2fba7e97/62f28282/video/tos/cn/tos-cn-v-0064/6f90040f1e9f43b29040dcbe7b3047d2/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4&bsxdisp=paco;https://v3-default.ixigua.com/c6a7e0318bbcc2e6e032337562e764e8/62f282bc/video/tos/cn/tos-cn-v-0064/04a44a3a0e7f405bbd84e6321441c6f6/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4;https://j8sbp6jqmi4ugbupnkmovbl4s20bqeo8l3r7ld273ag5q1l52u9fu2hm.tt.x.bsgslb.cn/xdispatch70f05392ddcca2ed/v9-default.ixigua.com/9e25e1faef08a10535c57af465640fc2/62f28157/video/tos/cn/tos-cn-v-0064/d441790ce4f646a6a948fd7feeb07ce0/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4&bsxdisp=paco;https://v3-default.ixigua.com/ab56b365eb1cb84092fdf52b8ff8209f/62f280af/video/tos/cn/tos-cn-v-0064/1987ed38f6ed463b85d159ce7aa9673e/?zxzjtv&filename=540P.mp4?zxzjtv&filename=1.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
