name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=20:w=1100:h=220"
                        INDEX: 21
                        EPISODE_INDEX: 5,6,7,8
                        START: https://zxzj.vip/video/3913-1-
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
