name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 14
                        EPISODE_INDEX: 25,26,27,28,29,30
                        URLS: https://v6-default.ixigua.com/e189cad28ecb87499ae9fe5f98f749ec/62f37dee/video/tos/cn/tos-cn-v-0064/81805df9b00e4378898be0e1a6a433fa/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/5274391708254ea4f52f7478cd665dad/62f37e15/video/tos/cn/tos-cn-v-0064/a45dfd0beb2f454ca9141530a20941b0/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/99712d185df7107401b010ebbddc8134/62f3800b/video/tos/cn/tos-cn-v-0064/11412be2ea324f8e830920192ca24932/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/606f6e1f6525fc5cd560896225fd3750/62f38016/video/tos/cn/tos-cn-v-0064/e40199d6d1ac41ba847955f1d062886e/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/21296f88e69470c54ce98bbfd5d3677b/62f37fe5/video/tos/cn/tos-cn-v-0064/5ad4dcb6852545aa83d28057c32c6d85/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/e5076ffe0859f63ce6f2937f5a91128f/62f37fd3/video/tos/cn/tos-cn-v-0064/273eb6d947e34122b4182b7fdb54bc7f/?tg=?zxzj.vip&filename=540P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
