name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=15:w=1100:h=220"
                        INDEX: 19
                        EPISODE_INDEX: 1,2,3,4,5,6
                        URLS: https://v26-default.ixigua.com/4e33172865051f48511b4dbca6344660/62f3d38e/video/tos/cn/tos-cn-v-0064/11983f1d9f384a859beabd465eb0a87a/?tg=?zxzj.vip&filename=1080P.mp4;https://v3-default.ixigua.com/e00470bfb1e9afe0b398ffcfc506e1ad/62f3d58b/video/tos/cn/tos-cn-v-0064/4e65e09c08d74c8694c91adc62890a48/?tg=?zxzj.vip&filename=1080P.mp4;https://ihsdkahbh7a6672ni86e95lfmijgdfjcdr5oiu1imnrrr5t03rcfv6u9.tt.x.bsgslb.cn/xdispatch70f05392d35b4c1f/v9-default.ixigua.com/a76648de1322998684feb38936c9636c/62f3d4ba/video/tos/cn/tos-cn-v-0064/df1f1c5e59c441f7839460f1bf3c3b5b/?tg=?zxzj.vip&filename=1080P.mp4&bsxdisp=paco;https://v6-default.ixigua.com/266845ecbd0c23715495462ee43f756c/62f3d4d9/video/tos/cn/tos-cn-v-0064/a7648bf721fd4680b21e37820a21e67c/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/a009a730d5b14953f2289af9faca9a2d/62f3d227/video/tos/cn/tos-cn-v-0064/4af7c536952a49c3932123913c627526/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/5d789411a4abea4a358b633c6fbdf72b/62f3d54a/video/tos/cn/tos-cn-v-0064/0460ef35c8f94863a8faad38300c6090/?tg=?zxzj.vip&filename=1080P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
