name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=15:w=1100:h=220"
                        INDEX: 16
                        EPISODE_INDEX: 13,14,15
                        URLS: https://v26-default.ixigua.com/68d26873b7e41d4feaa3fe34757f87e1/62f3c5c7/video/tos/cn/tos-cn-v-0064/d12f933866754b08a933780f8fef91cb/?tg=?zxzj.vip&filename=1080P.mp4;https://b57httotov5jvljnitq35c0rdp8ots1mg3tmors881epks2hoq2fu2r4.tt.x.bsgslb.cn/xdispatch70f053927c848a71/v9-default.ixigua.com/4174266de5b29c7420dfcd137c0011e9/62f3c687/video/tos/cn/tos-cn-v-0064/979c43b4d4c34267824275d642d40478/?tg=?zxzj.vip&filename=1080P.mp4&bsxdisp=paco;https://j3vrn7okq5qkflpmhjqr5rt8s3fl6msmo0c96dv32ldnvd7agdnvu3g6.tt.x.bsgslb.cn/xdispatch70f053927c848a71/v9-default.ixigua.com/f444eb3846ad3bfc3bf0cd48cc1a3c49/62f3c698/video/tos/cn/tos-cn-v-0064/e13dd0a055d6493d8ce3a4e33aa33eea/?tg=?zxzj.vip&filename=1080P.mp4&bsxdisp=paco
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
