name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 12
                        EPISODE_INDEX: 13,14,15,16,17,18,19
                        URLS: https://3pldkd8njq6eu1ij37d936leu6brbsre7v3ev8nm4fksidbdfgtvvrg2.tt.x.bsgslb.cn/xdispatch70f053927b827af7/v9-default.ixigua.com/9c19f7af13e7e36df3c64ca563d034ab/62f35aef/video/tos/cn/tos-cn-v-0064/fd1c9ac657f341ce9a417ee019d4bed7/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v6-default.ixigua.com/3d104a35141df91b5a3d9a8e9c69a8cd/62f35af0/video/tos/cn/tos-cn-v-0064/a004429d5db9460586a0891eac607d97/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/a4ca44cdc75d2e34a0b2b108bcd4dd98/62f35b2b/video/tos/cn/tos-cn-v-0064/7640f9b54f73415db16716041bc09340/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/3baa6658728727066cb2a4f1dc49d4dc/62f35b29/video/tos/cn/tos-cn-v-0064/8c01428931914e26885d50ec9c35e42b/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/e8595e3ae1db412d197eac1c9cd68b4a/62f360ee/video/tos/cn/tos-cn-v-0064/282bd43adbde4e8c8200a4cd4b1a211f/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/f5445d1d847a8bc44568c088efa004a7/62f35b6d/video/tos/cn/tos-cn-v-0064/04ded6f397e9484284b044353346152b/?tg=?zxzj.vip&filename=540P.mp4;https://fe2dd8lpc14084rkemrkogqqbnau7s0875v7vnrbaskpneqhpphfvbbo.tt.x.bsgslb.cn/xdispatch70f053927b827af7/v9-default.ixigua.com/2a9459a4facd7b55fe961e661c797b43/62f35b4a/video/tos/cn/tos-cn-v-0064/bc264852697c4a5f8a6d22a29643cb90/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
