name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=10:w=1100:h=200"
                        TBN: 24K
                        INDEX: 8
                        EPISODE_INDEX: 6,7
                        URLS: https://v3-default.ixigua.com/1dc720a6d4bab4773fc1acd576246e1a/62f2275e/video/tos/cn/tos-cn-v-0064/e74ce8655d96472fa90ce4b167d5a624/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v6-default.ixigua.com/1d5d53b7f789b1aaa9f4e0bb57416c4a/62f22a94/video/tos/cn/tos-cn-v-0064/7f8b1d79ac3c41e7ac7aa4f6e475ff5c/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
