name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=10:w=1100:h=200"
                        INDEX: 10
                        EPISODE_INDEX: 9,10,11
                        URLS: https://v26-default.ixigua.com/cb6b2c29b8f85638d7f645a7e24ebfb9/62f35505/video/tos/cn/tos-cn-v-0064/1e83028a60954928af30643ff22909f5/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/91ee599a58ab1f0a6f6453219a9b2cda/62f3529a/video/tos/cn/tos-cn-v-0064/233dc5a405ee49cb8063aa6a01ec082d/?tg=?zxzj.vip&filename=1080P.mp4;https://v6-default.ixigua.com/5ec17a476a2debb7b06045176a8c1729/62f353ff/video/tos/cn/tos-cn-v-0064/71df7c21015f4cc693b7cf3e4189cc83/?tg=?zxzj.vip&filename=1080P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
