name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 13
                        EPISODE_INDEX: 11,12,13,14,15,16,17,18,19,20,21
                        URLS: https://sanr08np3qm0csudplb5qu288t6ntpu41t3mqedsuhss1h8qsslfunjd.tt.x.bsgslb.cn/xdispatch70f0539270554698/v9-default.ixigua.com/d0445783ae1a8081fa139f72d5fb6534/62f3623a/video/tos/cn/tos-cn-v-0064/e6a0bc0073eb4dbb816499e5d18ed55e/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco&bsxdisp=paco;https://lp6sb0glg6a4g7ioianrhe76upu1ofv5fg3ofclr3sm5hcf6rtlvvvkp.tt.x.bsgslb.cn/xdispatch70f0539270554698/v9-default.ixigua.com/45d30fe2fa4ef527fb7c7d9a6be50e44/62f362b5/video/tos/cn/tos-cn-v-0064/bf5d4bd0e0cf41b1955ae670193abc45/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v3-default.ixigua.com/b0529d6b0dee7a5129b35ba9d9f70846/62f3628a/video/tos/cn/tos-cn-v-0064/c88761c9a963459dae8ac385fa9649e1/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/2d4255fb75d30214bdecbb458702b253/62f362d7/video/tos/cn/tos-cn-v-0064/e06024b0f0ca462890a37313224b35f9/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/3cce61912d45283f1a393b2549fb9d76/62f36286/video/tos/cn/tos-cn-v-0064/e9623cf6d5254675817822202ae88ae8/?tg=?zxzj.vip&filename=540P.mp4;https://j3vrn7okq5qkflpmhjqr5rt8s3fl6msmo0c96dv32ldnvd7agdnvu3g6.tt.x.bsgslb.cn/xdispatch70f0539270554698/v9-default.ixigua.com/f79e48147e0bc924855dac792571e95e/62f362e1/video/tos/cn/tos-cn-v-0064/35890020e4bd4248b82fa0f0e712444c/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v26-default.ixigua.com/cf4b9ba047d5b704e35468792156b5a3/62f362bf/video/tos/cn/tos-cn-v-0064/f5cb748e1e9542079867ecd0363cf811/?tg=?zxzj.vip&filename=540P.mp4;https://fe2dd8lpc14084rkemrkogqqbnau7s0875v7vnrbaskpneqhpphfvbbo.tt.x.bsgslb.cn/xdispatch70f0539270554698/v9-default.ixigua.com/ab1577e41495ee59ba14945cd7efdcf1/62f361ba/video/tos/cn/tos-cn-v-0064/1ac44d045ced4290a9e1193bf41f0a44/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v3-default.ixigua.com/82a657a964a8098d22c7926dfe9eb65d/62f3629e/video/tos/cn/tos-cn-v-0064/f63a2e50f0a748da892abe6ed4b9e83f/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/3708a6c5cc7bdc335e414ff74d77a10a/62f36303/video/tos/cn/tos-cn-v-0064/7622b6115a854a49b661a9331d2b6ff5/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/bede8044d1d42da56ad43059800c8da1/62f36938/video/tos/cn/tos-cn-v-0064/a77d420dfb094d6b9cae03786d059daa/?tg=?zxzj.vip&filename=540P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
