name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=10:w=1100:h=200"
                        INDEX: 9
                        EPISODE_INDEX: 6,7
                        URLS: https://v26-default.ixigua.com/394b5592059be3accb6ebde620314c6e/62f24099/video/tos/cn/tos-cn-v-0064/1b80a2ca4df4449197c01c0d6d7bfb19/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v6-default.ixigua.com/45b14b9e3a540e017074addfd0c09e1d/62f2409e/video/tos/cn/tos-cn-v-0064/c30e9a3907a74f9282e42d8ff4d4bbdf/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
