name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 15
                        EPISODE_INDEX: 14,15,16,17,18,19,20,21,22,23,24,25,26
                        URLS: https://v3-default.ixigua.com/b9b165485cb88160d1ca7035460d12bf/62f389e4/video/tos/cn/tos-cn-v-0064/6ec06411a97a4606a7e7bd64ed7cc6e3/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/8958cb64a5871e71465ac9f28d5c778a/62f389d2/video/tos/cn/tos-cn-v-0064/38c6e0425a29438cbc5746ad515afc7a/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/d7cb08436a7b0b0eaf4a69006d06e0d9/62f389dd/video/tos/cn/tos-cn-v-0064/588f5663574b451fa6e0949dd7214359/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/b5220d21791abc398c5aed50e73205e9/62f389ca/video/tos/cn/tos-cn-v-0064/47c27a7d58c94953aac9a2e5de5c7ba4/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/e5c3962ac7b6b697cae40d155f26d0c3/62f38a1f/video/tos/cn/tos-cn-v-0064/be2aa0ead92444ecad4120db06924cb4/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/7c693dedac0f54e14328c8cf47c45aff/62f38a1c/video/tos/cn/tos-cn-v-0064/39165be7e25d4826b3c9270aa92cc093/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/44823158fe295a7ca024a9781d90d755/62f38a27/video/tos/cn/tos-cn-v-0064/74a5436d373f4517821cc1bb7fc32f04/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/3656ab832a12bb4604b36bac559bad33/62f38a31/video/tos/cn/tos-cn-v-0064/91bff1caf92f47fa83bec30ead35db13/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/252457c2318f13cdf986ebf8ee913e69/62f38a3c/video/tos/cn/tos-cn-v-0064/bc76af78757b46c39b8b3578e7209061/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/470b3b5812c6b5a742c2143bb44fcd16/62f38a28/video/tos/cn/tos-cn-v-0064/d2cd3e0b297f4ff187be313cd22ecfd7/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/81eae2cf4087c38b23f96019a2e91abd/62f38a50/video/tos/cn/tos-cn-v-0064/9c11144c6775484b996d21e23d7c8a92/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/a892a6e431e8872e6eb4be8ba394a1f3/62f38a5a/video/tos/cn/tos-cn-v-0064/d192e6985dd34c27aa6010073ba240b6/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/beb22f043e4c8a167bb5395edddafc06/62f38a54/video/tos/cn/tos-cn-v-0064/e400f0f7ad1f4d87ab471503c53ce3e2/?tg=?zxzj.vip&filename=540P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
