name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=15:w=1100:h=220"
                        INDEX: 18
                        EPISODE_INDEX: 6,7,8
                        URLS: https://v26-default.ixigua.com/dd0c42366b6b5a45f4476e5dd64f3e1e/62f3cf53/video/tos/cn/tos-cn-v-0064/0d3bf615167543cfbc682a8283d9a33f/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/ff7f8c3ac1be373b48d7894a85cdeaaa/62f3ceca/video/tos/cn/tos-cn-v-0064/3d904c6cb3ac4643a246af6772f4f792/?tg=?zxzj.vip&filename=1080P.mp4;https://v3-default.ixigua.com/6009d03640de88fb5554db11d25b1128/62f3d1bd/video/tos/cn/tos-cn-v-0064/70199225365146aa96fa1b30245c612b/?tg=?zxzj.vip&filename=1080P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
