name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 15
                        EPISODE_INDEX: 1,2,3,4,5,6,7,8,9,10,11,12,13
                        URLS: https://v26-default.ixigua.com/104705fa1d33cb95c72b35adac9087f9/62f380d3/video/tos/cn/tos-cn-v-0064/f76e507757634b6cabff48f404ebf6ce/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/efe5686dd88a81c504fb9532f0067f31/62f38219/video/tos/cn/tos-cn-v-0064/9d0fa06d322f4616b13cb93a512fe47d/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/3cbea93819a032f0129d45cce7a8b2c5/62f38048/video/tos/cn/tos-cn-v-0064/f5363d27268a4325a33a5c7cc7699e70/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/f1b1d2d25c3cb9ce88c3b6bc1a5a5c97/62f38046/video/tos/cn/tos-cn-v-0064/66eb01f89fd045ab879e33d4b8b9db26/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/771ef45598f58a46bfb0de3fdd07a366/62f382ba/video/tos/cn/tos-cn-v-0064/811af8efae0b4154b27facb270f9fefc/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/495df4199f96a9da9c879d6d7733dc25/62f38273/video/tos/cn/tos-cn-v-0064/d31781df53964c8b83d8e9439925c124/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/58ab0c4eb82d51b04163a6f830eec06b/62f3810c/video/tos/cn/tos-cn-v-0064/fd36d3924e1a40788064b596399fbe1c/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/1b2b0f0750655782bc8e6281e6be4aa7/62f3828d/video/tos/cn/tos-cn-v-0064/087844eb3b1d4f7b8a80816eac0d5801/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/2a17eba99235f52b6084eba4aa4060f2/62f382a6/video/tos/cn/tos-cn-v-0064/c068f0fa02694c4f9c876eef3b60386b/?tg=?zxzj.vip&filename=540P.mp4;https://v9-default.ixigua.com/9cd7583d1a6f8b2fad717449a01abd56/62f382ba/video/tos/cn/tos-cn-v-0064/0b07b229dd354b31839df5b5bf92e530/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/a03e13d617110ffd1d6938995bdcd928/62f382c4/video/tos/cn/tos-cn-v-0064/51aab981b0bf468dbd3de4508eef1bf0/?tg=?zxzj.vip&filename=540P.mp4;https://v3-default.ixigua.com/d44812c9ae688b3f3e2b3a1775f8d91a/62f382ce/video/tos/cn/tos-cn-v-0064/c05ba65f53c9498f9c1005bb1d71c740/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/7c9b760b6c47160f9aec2c3673580ab0/62f382d8/video/tos/cn/tos-cn-v-0064/606cb382b60049a39fa5f9b8a1de983a/?tg=?zxzj.vip&filename=540P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
