name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=10:w=1100:h=200"
                        INDEX: 10
                        EPISODE_INDEX: 6,7,8,9,10,11
                        URLS: https://v9-default.ixigua.com/6fac72148d5497018b4b81f35230447b/62f27b75/video/tos/cn/tos-cn-v-0064/0b3ce205568342bda5236ba645510e0d/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v26-default.ixigua.com/9b4ae8662e1b58f8da909afa6b3b154d/62f27d5c/video/tos/cn/tos-cn-v-0064/f07add7f76e1413f88f589d9f60aa069/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v9-default.ixigua.com/60cb70bb1b60226725f50ad8bd088ed9/62f27c67/video/tos/cn/tos-cn-v-0064/2a8fc1bcb9de4d6ab765d528b7ad3423/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v9-default.ixigua.com/2995b51e1cf8047e83f35781669843f5/62f27d14/video/tos/cn/tos-cn-v-0064/1e83028a60954928af30643ff22909f5/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v3-default.ixigua.com/2b65e6dc500653a162c866f633b6e246/62f27dd0/video/tos/cn/tos-cn-v-0064/233dc5a405ee49cb8063aa6a01ec082d/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4;https://v6-default.ixigua.com/5b0ec44a1af8f10f8ad159856a716520/62f27e7f/video/tos/cn/tos-cn-v-0064/71df7c21015f4cc693b7cf3e4189cc83/?zxzjtv&filename=1080P.mp4?zxzjtv&filename=1.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
