name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=38:y=1:w=110:h=20"
                        INDEX: 13
                        EPISODE_INDEX: 1,2,3,4,5,6,7,8,9,10
                        URLS: https://jge027nimn5ohbu4f31aj0vgqiq9up4qbim4g52roppru4g04nhvvss8.tt.x.bsgslb.cn/xdispatch70f053927b800d9c/v9-default.ixigua.com/b999b31657000fa8d40df034481be40d/62f36175/video/tos/cn/tos-cn-v-0064/b9d03d1d701544988da16ee4eb9f816a/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v6-default.ixigua.com/ab5f6d10759cc843e4e352dd4ea24b72/62f360f8/video/tos/cn/tos-cn-v-0064/38c45f8b88bd4cf6830d055159816f7e/?tg=?zxzj.vip&filename=540P.mp4;https://hd6fsjjmt0qlspschk52jlk149rb0l6o6ioesneo8u516de1ngbvu6r3.tt.x.bsgslb.cn/xdispatch70f053927b800d9c/v9-default.ixigua.com/c05029aface211fa02a92cea4956f889/62f3615e/video/tos/cn/tos-cn-v-0064/6933f950ce0746a5823a869d34107d87/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v26-default.ixigua.com/7082ad34a7ba6351be62b81f992af21c/62f3612c/video/tos/cn/tos-cn-v-0064/c4f288f4d9a6412f8a73939f0aa2c66c/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/62b60c75e887d2fb1870a551c4468b01/62f3615b/video/tos/cn/tos-cn-v-0064/8217d5b7428e46499e084579aa311c58/?tg=?zxzj.vip&filename=540P.mp4;https://cdulfs804nplkdd7t20qh5lm3f52h9iac2fe2g6p4phu75ve51ifuui6.tt.x.bsgslb.cn/xdispatch70f053927b800d9c/v9-default.ixigua.com/674407d52a3be284a0735c667e1f3e52/62f3615c/video/tos/cn/tos-cn-v-0064/509973e6d4de49db86f45dbf67a4eab7/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco;https://v6-default.ixigua.com/8def51bb5a5671f3fe599eb9b47f13b3/62f36793/video/tos/cn/tos-cn-v-0064/301d0463a3aa41d0a837be39f1e95438/?tg=?zxzj.vip&filename=540P.mp4;https://v26-default.ixigua.com/11f376b9b0b433721eb3a7175611d364/62f36193/video/tos/cn/tos-cn-v-0064/5c951631544c47ccae851c78d9263f53/?tg=?zxzj.vip&filename=540P.mp4;https://v6-default.ixigua.com/d21b5eadf3f0d16ce4df08b30af6185c/62f3619f/video/tos/cn/tos-cn-v-0064/73616cf1c64b488eb40259d6ca429e88/?tg=?zxzj.vip&filename=540P.mp4;https://osuemg0keqb95cb2cf1ktqc5ntsh3m1a40tni51058bmv6ctk61fubde.tt.x.bsgslb.cn/xdispatch70f053927b800d9c/v9-default.ixigua.com/320b1d150dda80e5f70bd4ed662ebb21/62f3617f/video/tos/cn/tos-cn-v-0064/52e2c68cb944428fbe164eeffc303c4e/?tg=?zxzj.vip&filename=540P.mp4&bsxdisp=paco
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
