name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=15:w=1100:h=220"
                        INDEX: 16
                        EPISODE_INDEX: 1,2,3,4,5,6,7
                        URLS: https://v6-default.ixigua.com/408be0a61206b6f12799d7d44901c715/62f3ac51/video/tos/cn/tos-cn-v-0064/3f14c4c89dce4362877f9fbb046a9a1d/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/437290d87ad9f6e246a9e44b5ea0cf46/62f3ac6d/video/tos/cn/tos-cn-v-0064/aec2f9944ad241a5867e5b32ee8cdd16/?tg=?zxzj.vip&filename=1080P.mp4;https://v6-default.ixigua.com/5bf08fe2c8529f0e1289bb1e4296d5c5/62f3ac81/video/tos/cn/tos-cn-v-0064/a6ed9e95cc9147728928cefa2d6f9bdb/?tg=?zxzj.vip&filename=1080P.mp4;https://v3-default.ixigua.com/f91f2a375ae14c69f3e13dd3112f2281/62f3accf/video/tos/cn/tos-cn-v-0064/a96ae06159aa42c59461bf1cc2a0d0c1/?tg=?zxzj.vip&filename=1080P.mp4;https://v3-default.ixigua.com/acafec5e5437c88a359dd2ecf88f5673/62f3ac8f/video/tos/cn/tos-cn-v-0064/02746eda13ca474abc6347cf39ceda28/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/0015b601045a6de51a374cad7e0137c1/62f3aca1/video/tos/cn/tos-cn-v-0064/4f77ad5b53c64af8b5c19734d7a1e3c2/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/324e77f7a15367304cac60ec01d94cc3/62f3acd4/video/tos/cn/tos-cn-v-0064/c86906f4f7514722aba3d5eefa3b096c/?tg=?zxzj.vip&filename=1080P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
