name: CI-movie4all


on:
        workflow_dispatch:

jobs:
        build:
                runs-on: ubuntu-latest

                env:
                        PROXIES: movie4all-proxy1;movie4all-proxy2;movie4all-proxy3;movie4all-proxy4;movie4all-proxy5
                        TIME: 00:00:10
                        POSITION: "delogo=x=380:y=25:w=1100:h=220"
                        INDEX: 20
                        EPISODE_INDEX: 7,8,9,10
                        URLS: https://v9-default.ixigua.com/dc2409e37084c6fb30a8db12c083248c/62f3e75e/video/tos/cn/tos-cn-v-0064/b9df1f03b0a64b2fa6adb338e24f1df1/?tg=?zxzj.vip&filename=1080P.mp4;https://v9-default.ixigua.com/f95c72253fa7b4791a71f1eb7a2ee405/62f3e84a/video/tos/cn/tos-cn-v-0064/e5d1f1e1e439442bbfb036414e3905aa/?tg=?zxzj.vip&filename=1080P.mp4;https://v26-default.ixigua.com/89ba01390e8d9a2c354059ba08a98df5/62f3e837/video/tos/cn/tos-cn-v-0064/b202dcf755964fe6b5ab84fb3d3ef785/?tg=?zxzj.vip&filename=1080P.mp4;https://v6-default.ixigua.com/c10c8d9808369fdfce137388071915da/62f3ea93/video/tos/cn/tos-cn-v-0064/f3b60e46bbe04f28b4ecff578fb4dff8/?tg=?zxzj.vip&filename=1080P.mp4
                steps:
                - name: setup go
                  uses: actions/checkout@v2
                  with:
                        go-version: '1.16.0'
                - name: install dependencied
                  run:  go mod init movie
                - name: tidy
                  run: go mod tidy
                - name: install ffmpeg
                  run: sudo apt install ffmpeg -y
                - name: Run
                  run: go run main.go
